# including default.yaml
defaults:
  - default
  - _self_

agent_workflow: "chain-of-agents"
async_workflow: false
workflow_func_path: null
processor_func_path: null

workflow_args:
  num_rounds: 1

chat_template: null
agents:
  - agent_problem_solver:
      role: agent_problem_solver
  - agent_code_executor:
      role: agent_code_executor
      code_execution: true
  - agent_verifier:
      role: agent_verifier

tools_config:
  max_turns: 2
  num_workers: 128
  enable_metrics: True
  enable_rate_limiting: True
  tools:
    code_interpreter:
      type: sandbox_fusion
      enable_rate_limiting: True
      rate_limit: 30
      timeout: 30
      base_url: "http://127.0.0.1:8080/run_code"
      schema_path: "examples/schema/code.json"

